// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzhbetzkstoghubeolku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6aGJldHprc3RvZ2h1YmVvbGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjYwMTEsImV4cCI6MjA3MTkwMjAxMX0.0Xct-Go6UIF31RfFUJtIjGT5XI52H4ZszCTZXxDbQ5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});